#include "lua_native_binding.hpp"
#include "natives.hpp"

namespace lua::native
{
	static int LUA_NATIVE_LOCALIZATION_LOCALIZATION_GET_SYSTEM_LANGUAGE()
	{
		auto retval = LOCALIZATION::LOCALIZATION_GET_SYSTEM_LANGUAGE();
		return retval;
	}

	static int LUA_NATIVE_LOCALIZATION_GET_CURRENT_LANGUAGE()
	{
		auto retval = LOCALIZATION::GET_CURRENT_LANGUAGE();
		return retval;
	}

	static int LUA_NATIVE_LOCALIZATION_LOCALIZATION_GET_SYSTEM_DATE_TYPE()
	{
		auto retval = LOCALIZATION::LOCALIZATION_GET_SYSTEM_DATE_TYPE();
		return retval;
	}

	void init_native_binding_LOCALIZATION(sol::state& L)
	{
		auto LOCALIZATION = L["LOCALIZATION"].get_or_create<sol::table>();
		LOCALIZATION.set_function("LOCALIZATION_GET_SYSTEM_LANGUAGE", LUA_NATIVE_LOCALIZATION_LOCALIZATION_GET_SYSTEM_LANGUAGE);
		LOCALIZATION.set_function("GET_CURRENT_LANGUAGE", LUA_NATIVE_LOCALIZATION_GET_CURRENT_LANGUAGE);
		LOCALIZATION.set_function("LOCALIZATION_GET_SYSTEM_DATE_TYPE", LUA_NATIVE_LOCALIZATION_LOCALIZATION_GET_SYSTEM_DATE_TYPE);
	}
}
