#include "backend/command.hpp"
#include "natives.hpp"

namespace big
{
	class fill_ammo : command
	{
		using command::command;

		virtual void execute(const std::vector<std::uint64_t>&, const std::shared_ptr<command_context> ctx)
		{
			int AMMO_PISTOL, AMMO_SMG, AMMO_RIFLE, AMMO_MG, AMMO_SHOTGUN, AMMO_STUNGUN, AMMO_SNIPER, AMMO_SNIPER_REMOTE, AMMO_GRENADELAUNCHER, AMMO_GRENADELAUNCHER_SMOKE, AMMO_RPG, AMMO_STINGER, AMMO_MINIGUN, AMMO_GRENADE, AMMO_STICKYBOMB, AMMO_SMOKEGRENADE, AMMO_BZGAS, AMMO_MOLOTOV, AMMO_FIREEXTINGUISHER, AMMO_PETROLCAN, AMMO_BALL, AMMO_FLARE, AMMO_TANK, AMMO_SPACE_ROCKET, AMMO_PLANE_ROCKET, AMMO_PIPEBOMB, AMMO_HOMINGLAUNCHER, AMMO_PROXMINE, AMMO_SNOWBALL, AMMO_RIFLE_ARMORPIERCING, AMMO_RIFLE_FMJ, AMMO_RIFLE_INCENDIARY,AMMO_RIFLE_TRACER, AMMO_SNIPER_ARMORPIERCING, AMMO_SNIPER_FMJ, AMMO_SNIPER_INCENDIARY, AMMO_SNIPER_TRACER, AMMO_SHOTGUN_ARMORPIERCING, AMMO_SHOTGUN_EXPLOSIVE, AMMO_SHOTGUN_HOLLOWPOINT,AMMO_SHOTGUN_INCENDIARY,AMMO_PISTOL_FMJ,AMMO_PISTOL_HOLLOWPOINT,AMMO_PISTOL_INCENDIARY, AMMO_PISTOL_TRACER, AMMO_MG_ARMORPIERCING, AMMO_MG_FMJ, AMMO_MG_INCENDIARY, AMMO_MG_TRACER, AMMO_SNIPER_EXPLOSIVE, AMMO_SMG_FMJ, AMMO_SMG_HOLLOWPOINT, AMMO_SMG_INCENDIARY, AMMO_SMG_TRACER, AMMO_FLAREGUN, AMMO_FIREWORK, AMMO_RAILGUN;

			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL"), &AMMO_PISTOL);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL"), AMMO_PISTOL);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG"), &AMMO_SMG);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG"), AMMO_SMG);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE"), &AMMO_RIFLE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE"), AMMO_RIFLE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG"), &AMMO_MG);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG"), AMMO_MG);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN"), &AMMO_SHOTGUN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN"), AMMO_SHOTGUN);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STUNGUN"), &AMMO_STUNGUN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STUNGUN"), AMMO_STUNGUN);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER"), &AMMO_SNIPER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER"), AMMO_SNIPER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_REMOTE"), &AMMO_SNIPER_REMOTE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_REMOTE"), AMMO_SNIPER_REMOTE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADELAUNCHER"), &AMMO_GRENADELAUNCHER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADELAUNCHER"), AMMO_GRENADELAUNCHER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADELAUNCHER_SMOKE"), &AMMO_GRENADELAUNCHER_SMOKE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADELAUNCHER_SMOKE"), AMMO_GRENADELAUNCHER_SMOKE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RPG"), &AMMO_RPG);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RPG"), AMMO_RPG);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STINGER"), &AMMO_STINGER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STINGER"), AMMO_STINGER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MINIGUN"), &AMMO_MINIGUN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MINIGUN"), AMMO_MINIGUN);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADE"), &AMMO_GRENADE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_GRENADE"), AMMO_GRENADE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STICKYBOMB"), &AMMO_STICKYBOMB);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_STICKYBOMB"), AMMO_STICKYBOMB);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMOKEGRENADE"), &AMMO_SMOKEGRENADE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMOKEGRENADE"), AMMO_SMOKEGRENADE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_BZGAS"), &AMMO_BZGAS);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_BZGAS"), AMMO_BZGAS);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MOLOTOV"), &AMMO_MOLOTOV);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MOLOTOV"), AMMO_MOLOTOV);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FIREEXTINGUISHER"), &AMMO_FIREEXTINGUISHER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FIREEXTINGUISHER"), AMMO_FIREEXTINGUISHER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PETROLCAN"), &AMMO_PETROLCAN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PETROLCAN"), AMMO_PETROLCAN);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_BALL"), &AMMO_BALL);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_BALL"), AMMO_BALL);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FLARE"), &AMMO_FLARE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FLARE"), AMMO_FLARE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_TANK"), &AMMO_TANK);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_TANK"), AMMO_TANK);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SPACE_ROCKET"), &AMMO_SPACE_ROCKET);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SPACE_ROCKET"), AMMO_SPACE_ROCKET);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PLANE_ROCKET"), &AMMO_PLANE_ROCKET);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PLANE_ROCKET"), AMMO_PLANE_ROCKET);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PIPEBOMB"), &AMMO_PIPEBOMB);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PIPEBOMB"), AMMO_PIPEBOMB);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_HOMINGLAUNCHER"), &AMMO_HOMINGLAUNCHER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_HOMINGLAUNCHER"), AMMO_HOMINGLAUNCHER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PROXMINE"), &AMMO_PROXMINE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PROXMINE"), AMMO_PROXMINE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNOWBALL"), &AMMO_SNOWBALL);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNOWBALL"), AMMO_SNOWBALL);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_ARMORPIERCING"), &AMMO_RIFLE_ARMORPIERCING);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_ARMORPIERCING"), AMMO_RIFLE_ARMORPIERCING);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_FMJ"), &AMMO_RIFLE_FMJ);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_FMJ"), AMMO_RIFLE_FMJ);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_INCENDIARY"), &AMMO_RIFLE_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_INCENDIARY"), AMMO_RIFLE_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_TRACER"), &AMMO_RIFLE_TRACER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RIFLE_TRACER"), AMMO_RIFLE_TRACER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_ARMORPIERCING"), &AMMO_SNIPER_ARMORPIERCING);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_ARMORPIERCING"), AMMO_SNIPER_ARMORPIERCING);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_FMJ"), &AMMO_SNIPER_FMJ);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_FMJ"), AMMO_SNIPER_FMJ);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_INCENDIARY"), &AMMO_SNIPER_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_INCENDIARY"), AMMO_SNIPER_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_TRACER"), &AMMO_SNIPER_TRACER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_TRACER"), AMMO_SNIPER_TRACER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_ARMORPIERCING"), &AMMO_SHOTGUN_ARMORPIERCING);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_ARMORPIERCING"), AMMO_SHOTGUN_ARMORPIERCING);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_EXPLOSIVE"), &AMMO_SHOTGUN_EXPLOSIVE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_EXPLOSIVE"), AMMO_SHOTGUN_EXPLOSIVE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_HOLLOWPOINT"), &AMMO_SHOTGUN_HOLLOWPOINT);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_HOLLOWPOINT"), AMMO_SHOTGUN_HOLLOWPOINT);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_INCENDIARY"), &AMMO_SHOTGUN_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SHOTGUN_INCENDIARY"), AMMO_SHOTGUN_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_FMJ"), &AMMO_PISTOL_FMJ);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_FMJ"), AMMO_PISTOL_FMJ);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_HOLLOWPOINT"), &AMMO_PISTOL_HOLLOWPOINT);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_HOLLOWPOINT"), AMMO_PISTOL_HOLLOWPOINT);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_INCENDIARY"), &AMMO_PISTOL_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_INCENDIARY"), AMMO_PISTOL_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_TRACER"), &AMMO_PISTOL_TRACER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_PISTOL_TRACER"), AMMO_PISTOL_TRACER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_ARMORPIERCING"), &AMMO_MG_ARMORPIERCING);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_ARMORPIERCING"), AMMO_MG_ARMORPIERCING);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_FMJ"), &AMMO_MG_FMJ);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_FMJ"), AMMO_MG_FMJ);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_INCENDIARY"), &AMMO_MG_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_INCENDIARY"), AMMO_MG_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_TRACER"), &AMMO_MG_TRACER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_MG_TRACER"), AMMO_MG_TRACER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_EXPLOSIVE"), &AMMO_SNIPER_EXPLOSIVE);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SNIPER_EXPLOSIVE"), AMMO_SNIPER_EXPLOSIVE);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_FMJ"), &AMMO_SMG_FMJ);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_FMJ"), AMMO_SMG_FMJ);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_HOLLOWPOINT"), &AMMO_SMG_HOLLOWPOINT);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_HOLLOWPOINT"), AMMO_SMG_HOLLOWPOINT);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_INCENDIARY"), &AMMO_SMG_INCENDIARY);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_INCENDIARY"), AMMO_SMG_INCENDIARY);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_TRACER"), &AMMO_SMG_TRACER);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_SMG_TRACER"), AMMO_SMG_TRACER);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FLAREGUN"), &AMMO_FLAREGUN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FLAREGUN"), AMMO_FLAREGUN);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FIREWORK"), &AMMO_FIREWORK);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_FIREWORK"), AMMO_FIREWORK);
			WEAPON::GET_MAX_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RAILGUN"), &AMMO_RAILGUN);
			WEAPON::SET_PED_AMMO_BY_TYPE(self::ped, MISC::GET_HASH_KEY("AMMO_RAILGUN"), AMMO_RAILGUN);
		}
	};
	fill_ammo g_fill_ammo("fillammo", "Fill Ammo", "Fills all of your ammo.", 0);
}