name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: bug
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs
    description: |
      For a bug report to be valid, you need to include the logs for YimMenu.
      They can be found under `%appdata%/YimMenu/cout.log`, even if you think the log file is useless we'd still like for you to include it here.

      Tip: To easily upload your log file rename the cout.log file to cout.txt, alternatively zip the cout.log file. You can then drag and drop the file here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots / Video
    description: |
      If you think the issue can be better explained with screenshots or a video then consider adding these here.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    value: |
      <!-- drag and drop your images or video(s) here -->
  validations:
    required: false
- type: dropdown
  attributes:
    label: Store
    description: Which launcher/store do you use to launch your game?
    multiple: false
    options:
      - Steam
      - Epic Games
      - Rockstar
      - Other (please mention in "Additional context")
  validations:
    required: true
- type: dropdown
  attributes:
    label: Language
    description: Which language do you have GTA 5 set to?
    multiple: false
    options:
      - English
      - French
      - Italian
      - German
      - Spanish
      - Japanese
      - Russian
      - Polish
      - Brazilian Portuguese
      - Traditional Chinese
      - Simplified Chinese
      - Latin American Spanish
      - Korean
  validations:
    required: true
- type: dropdown
  attributes:
    label: YimMenu Language
    description: Which language do you use with YimMenu?
    multiple: false
    options:
      - English (US)
      - Español (España)
      - Français (FR)
      - Italiano (IT)
      - Portuguese (BR)
      - Русский (RU)
      - Chinese (CN)
      - Chinese (TW)
      - Korean (KR)
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Build
    description: We want to confirm that this issue exists on the latest version of YimMenu, not a fork or your own version of YimMenu.
    options:
      - label: I've confirmed the issue exists on the latest version of YimMenu
        required: true
- type: checkboxes
  attributes:
    label: Coload
    description: Make sure you test YimMenu without co-loading (Menyoo, Stand, ...) first and see if the issue exists, if it doesn't verify if you think the issue lies with us or with the product you're co-loading with.
    options:
      - label: I've tested this without co-loading anything.
        required: true
