name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: bug
assignees:
  - Yimura
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Scroll down to '...'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots and/or Logs
    description: "Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in."
    value: |
      ```
      <paste your logs here>
      ```
  validations:
    required: false
- type: dropdown
  attributes:
    label: Store
    description: Which launcher/store do you use to launch your game?
    multiple: false
    options:
      - Steam
      - Epic Games
      - Rockstar
      - Other (please mention in "Additional context")
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Build
    description: Make sure that this bug occurs on unmodified YimMenu
    options:
      - label: I used YimMenu unmodified
        required: true
