name: Feature request
description: Suggest an idea for this project
title: "[Request]: "
labels: request
body:
- type: textarea
  attributes:
    label: Problem
    description: "Is your feature request related to a problem? Please describe."
    placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  validations:
    required: false
- type: textarea
  attributes:
    label: Solution
    description: "Describe the solution you'd like"
    placeholder: "A clear and concise description of what you want to happen."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reason
    description: Provide Reasoning
    placeholder: "Tell us why you'd want for us to add this to YimMenu."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the request here.
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
