name: Update GTA Data

on:
  schedule:
    # cronjob that triggers every day at 2PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  update_gta_data:
    runs-on: ubuntu-latest
    name: Update GTA Data
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
      
      - name: checkout repo
        uses: actions/checkout@v2.4.2

      - name: Generate header files
        run: cd ".github/workflows/gen_gta_service_files" && npm ci && npm start
        
      - name: Move header files
        run: cd "./../../.." && ls && cp -R "./.github/workflows/gen_gta_service_files/dist/BigBaseV2" ./
        
      - name: Check if file exist
        run: ls BigBaseV2/src/services/gta_data

