name: Update GTA Data

on:
  schedule:
    # cronjob that triggers every day at 2PM UTC
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  update_gta_data:
    runs-on: ubuntu-latest
    name: Update GTA Data
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate premake5 project
        run: premake5 vs2019
        shell: bash

      - name: Build 64bit release DLL
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 BigBaseV2.sln /warnaserror

      - name: Rename DLL to YimMenu.dll
        run: ren BigBaseV2.dll YimMenu.dll
        working-directory: bin/Release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: |
            bin/Release/YimMenu.dll

      - name: Generate Build Info
        id: var
        run: |
          echo "::set-output name=full_sha::$(git rev-parse HEAD)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
