name: Sync with original

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull from original repo
      run: |
        git remote add upstream https://github.com/original_owner/original_repo.git
        git config pull.rebase true
        git pull upstream main

    - name: Push to forked repo
      run: |
        git push
