name: Sync with original

on:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.PAT }}

    - name: Pull from original repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add upstream https://github.com/YimMenu/YimMenu.git
        git fetch upstream
        git pull --rebase upstream master
        git push
